# docker-compose.yml

version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: "keinos/sqlite3:latest"
    volumes:
      - ./db:/var/lib/sqlite
